---
title: <span style='font-size:85%; font-weight:80'>Doutorado</span>
---

<br>

### Códigos em R

<br>

   - [Funções básicas](figs/funcoes1.txt){target="_blank"}
   - **Estudo bibliométrico**
     - [Banco de dados Web of Science](figs/web_data.bib){target="_blank"}
     - [Banco de dados Scopus](figs/scopus_data.bib){target="_blank"}
     - [Análise bibliométrica](figs/bibiometric_analysis.txt){target="_blank"}
   - **Tempos de estimativa MatSimpler:**
     - [Simulação](figs/MatSimpler_estimation_times_simulation.txt){target="_blank"}
     - [Gráfico](figs/MatSimpler_estimation_times_plot.txt){target="_blank"}
   - **Comparando tempos de estimativa:**
     - [Simulação](figs/Comparing_estimation_times_simulation.txt){target="_blank"}
     - [Gráfico](figs/Comparing_estimation_times_plot.txt){target="_blank"}
   - **Análise de dados:**
     - [Conjunto de dados bivariado do solo250](figs/soil250_estimation.txt){target="_blank"}
     - [conjunto de dados Meuse de 4 variáveis](figs/meuse_estimation.txt){target="_blank"}

<br>

### Apresentação

   - [Slides](figs/presentation_tese_2022.pdf){target="_blank"}
   
   
<style>
    body {
      font-size: 20px; /* Tamanho padrão para todo o corpo do documento */
    }
    p {
      font-size: 23px; /* Tamanho para parágrafos */
    }
    li {
      font-size: 23px; /* Tamanho para tópicos */
    }
     a:link {
        color: #00008B; /* Define a cor do link */
        text-decoration: none;
    }
    a:visited {
        color: #191970; /* Define a cor do link */
        text-decoration: none;
    }
    a:hover {
        color: 	#4682B4; /* Define a cor do link ao passar o mouse */
        text-decoration: none;
    }
    a:active {
        color: #8B008B; /* Define a cor do link ao ser clicado */
        text-decoration: none;
    }
</style>