# Manipulação de dados 

O objetivo deste capítulo é abordar métodos para a importação e manipulação de dados em diferentes formatos e de diferentes fontes. 

O primeiro passo é definir o diretório de trabalho. O diretório de trabalho é pasta padrão onde o R irá buscar os arquivos, caso queira acessar um arquivo que não esteja no diretório de trabalho é necessário informar o caminho do arquivo no computador. 

Para saber qual o diretório do seu computador utilize o comando ``getwd()`` na janela de comando. Para alterar o diretório de trabalho utilize o comando ``setwd()``, onde o argumento deve ser o caminho da pasta que você deseja que seja o diretório. 

## Leitura de arquivos de texto

Para a leitura de documetos de texto no formato ``.txt`` (texto sem formatação) ou ``.csv`` (texto separado por virgula) é utilizado os comando do pacote ``readr``. 

Suponha que queremos ler o arquivo "PoemaCarloDrummont.txt" que possuiu o seguinte conteúdo:

```
PoemaCarlosDrummond   N° de palavras
No meio do caminho tinha uma pedra    7 
tinha uma pedra no meio do caminho    7
tinha uma pedra   3
no meio do caminho tinha uma pedra.   7
Nunca me esquecerei desse acontecimento   5
na vida de minhas retinas tão fatigadas.    7
Nunca me esquecerei que no meio do caminho    8
tinha uma pedra   3
tinha uma pedra no meio do caminho    7
no meio do caminho tinha uma pedra.   7

```

O arquivo de texto contém um poema de Carlos Drummont e junto a quantidade de palavras por linha. Para ler o arquivo em R pode ser utilizado o comando ``read_delim("PoemaCarlosDrummond.txt",delim = "\t")``.

Para separar as informações foi utilizado a tecla Tab do teclado, o parâmetro ``delim = "\t"`` indica essa separação. Onde houver um Tab o comando vai divir em colunas diferentes. Então o arquivo será transformado em base de dados de 10 linhas e 2 colunas, a primeira linha é usada para nomear as colunas.   


Para arquivos separados com vírgula (``.csv``) podem ser usadas dois comando, o comando ``read_csv(file = "NomeDoArquivo.csv")`` ou ``read_csv2("NomeDoArquivo.csv")``. A principal diferença é que ``read_csv()`` é usado para arquivos separados com vírgula e ``read_csv2("NomeDoArquivo.csv")`` para arquivos separados com ponto e vírgula. 

## Leitura de planilhas 

Planilhas geralmente possuem extensão ``.xlsx`` ou ``.xls`` para ler arquivos neste formato podem ser usados os comando do pacote ``readxl``.

O principal comando é ``read_excel(path = CaminhoDoAquivo.xls)``, tanto faz o arquivo ter a extensão ``.xlsx`` ou ``.xls``, o comando entende as duas.

O pacote ``readxl`` possuiu 5 exemplos de arquivos ``.xlsx`` e ``.xls`` que podem ser acessados utilizando o comando ``readxl_example()``. Um desses arquivos exemplo é ``"datasets.xls"`` se executarmos o comando ``readxl_example("datasets.xls")`` ele irá retornar o caminho do arquivo ``"datasets.xls"`` no computador. Então podemos usar esse caminho para ler o seu conteúdo usando o comando ``read_excel()``.

Muitas vezes um arquivo ``.xlsx`` ou ``.xls`` é divido em varias planilhas, para saber se um arquivo possui varias planilhas utilize o comando ``excel_sheets("CaminhoDoArquivo")`` que retorna o nome de cada uma das planilhas.  

## Manipulação de dados

Após a importação e leitura de uma base de dados é importante trabalhar esses dados para que fiquem num formato mais fácil de serem analisados, plotados e facilitar o processo de inferência das informações. 

Dois pacotes pricipais são usados para a manipulação de dados, o pacote ``dplyr`` e o pacote ``tidyr``. 

Similares aos Data Frames outra estrutura de dados importante são os tibbles, que também são tabelas de informações oraganizadas em colunas, cada uma representando um atributo, mas diferente dos Data Frames sua visualização é mais simples. Para a criação de tibble pode ser utilizado o comando ``tibble()`` onde os argumentos serão vetores que representam as colunas. 


```
tibble(
    Nome = c("João","Pedro","Gabriel"),
    Altura = c(1.80,1.67,1.86),
    Idade = c(17,11,21),
    Peso = c(70,52,82)
)
```

Outra forma de criar tibble é transformar Data Frames em tibble utilizando a função ``as_tibble()``. O comando ``as_tibble()`` faz parte do pacote ``tibble`` que também possui comandos como ``add_row()`` para adcionar uma linha ou ``add_column()`` para adcionar coluna. 

```
T1 = tibble(
    Nome = c("João","Pedro","Gabriel"),
    Altura = c(1.80,1.67,1.86),
    Idade = c(17,11,21),
    Peso = c(70,52,82)
)

T1 %>% add_row(Nome = "Luis",Altura = 1.77, Idade = 18, Peso = 73)
```

O comando acima adciona uma nova linha ao tibble ``T1``. O comando ``%>%``, chamado de operador pipe, é uma maneira de passar um parâmetro para um comando. 

O objetivo do pacote ``dplyr`` é disponibilizar comandos que permitam manipular tibble de uma maneira simples. Um exemplo é o comando ``select(T1, Altura)`` que retorna somente a coluna ``Altura`` do tibble ``T1``. O comando ``arrange(T1, Peso)`` organiza as linhas do tibble ``T1`` em ordem crescente de acordo com os valores da coluna ``Peso``. 

Os comando do pacote ``tidyr`` complementam os comandos do pacote ``dplyr``. Dois principais comandos desse pacote são os comandos ``separate()`` e ``unite()``. O comando ``separate()`` separa uma coluna de um tibble em novas colunas de acordo com necessidades. O comando ``unite()`` realiza o processo inverso, é possivel juntar diferentes colunas em uma única. Para mais informações sobre os comandos desses pacotes utilize os comandos ``library(help = "dplyr")`` ou ``library(help = "tidyr")``.     

